### PR TITLE
Refactor payment renderer to call native placeOrderAction in order for extensions to work

### PR DESCRIPTION
**Pull request by unicoder88**
Hi!

I would like to introduce refactored version of payment renderer. My concern is that current implementation doesn't fulfil Magento payment method renderer contract and doesn't call js/action/place-order when you click "Place Order" button.

That action is important to be called, because firstly it contains a bit of core logic like choosing API endpoint url and managing loader, and more importantly this action is supposed to be used for extensions to modify paymentData. One example is Magento_CheckoutAgreements module.

vendor/magento/module-checkout-agreements/view/frontend/requirejs-config.js:
```javascript
var config = {
    config: {
        mixins: {
            'Magento_Checkout/js/action/place-order': {
                'Magento_CheckoutAgreements/js/model/place-order-mixin': true
            },
            'Magento_Checkout/js/action/set-payment-information': {
                'Magento_CheckoutAgreements/js/model/set-payment-information-mixin': true
            }
        }
    }
};
```

It is logical that other vendors might follow core checkout agreements example and add mixins to that action/place-order, and we already hit this boundary installing our OrderComment module. This is why I went ahead and used place-order in the flow. This allowed to get rid of some copy-pasted agreements code (let native module do its job). Another improvement is moving responsibility of storing paymentTypeId  to checkout-data component, so that renderer can focus on it's job.

Looking forward to your comments.

### CODE REVIEW

**Comment by maxwhite** [comment]
Hi, 
thanks for contribution. I've tried to test your branch "place-order-action" 
and it doesn't work. On checkout when I press one of cards radio button the payment method block will not expand, also in browser console I can see error: 
TypeError: checkoutData.setPaytypeId is not a function
Have you tested it ?

**Comment by unicoder88** [comment]
Hi! Thanks for checking.

Firstly, to get rid of "checkoutData.setPaytypeId is not a function" error just run `setup:static-content:deploy` or remove file `pub/static/_requirejs/frontend/{ThemeVendor}/{Theme}/{Locale}/requirejs-config.js`, This is because `requirejs-config.js` file was added.

Concerning payment form not showing up you're right. I blamed our custom checkout for this. This is now resolved and I also refactored payment method selection. It had a little problem with `checked: $parent.getDibsPaytype()` - this made one of Dibs methods checked after page refresh even when quote.paymentMethod was previously selected other than Dibs because it checked paytypeid and missed method check.

Anyway, please have a look.

**Comment by maxwhite** [comment]
Hi, thanks for changes. Tested it again, the same problem with form not showing up. 
Also if only Dibs payment method enabled and others are disabled Dibs method not showing at all

**Comment by unicoder88** [comment]
Hey!

I added preselection logic to facilitate standard Magento flow that when count payment methods == 1, this method is preselected. With Dibs we simply preselect first available payment type.

I'm confused why the form won't show for you, this must have something with Magento version? I tested on latest 2.1.3 CE only for now. I shot a video how it works for me: https://vimeo.com/200730108 , password `dibs`. Will test further on earlier versions - up to 2.1.0 or 2.0 I guess? I expect this pull request might be put on hold before that is done.

**Pull request closed without merging**
